### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by KYKong97** [Xujxyang/OpenTrans#1]
Hi is there any link I can download the pretrained model?

**Comment by Xujxyang** [comment]
Hi! You can obtain your own pretrained model through plain_train_net.py or train_net.py. Our pretrained model was trained for only 50,000 iterations(bs: 28), you can download [here](https://drive.google.com/file/d/1GowIiJqlyPXIzRnTEfIsJzzOgEa9LzRn/view?usp=drive_link). You can train a better one yourself!

**Comment by Y-Claw** [comment]
Could I ask another question. 
Which result in the paper does the checkpoint you provided here (https://drive.google.com/file/d/1GowIiJqlyPXIzRnTEfIsJzzOgEa9LzRn/view) correspond to, Table 1?

**Comment by Xujxyang** [comment]
IMP is performed on a pre-trained model rather than training from scratch, so this is our pre-trained model (according to Han et al.).
