### ISSUE TITLE
table 2

### ISSUE THREAD

**Issue by geek-APTX4869** [Xujxyang/OpenTrans#3]
Dear author：
  如何得到表2的结果呢，想学习一下

**Comment by Xujxyang** [comment]
This is where the $\alpha$ value is calculated. https://github.com/Xujxyang/OpenTrans/blob/aea33ff3682403aec6d55a670030d6cb4b0623cd/plain_train_net.py#L401
The results in Table 2 are solely about the ablation of $\alpha$ and are unrelated to the previous pruning. You can directly use this part of the code for training (as shown in the table, this method is applied after training for 10,000 iterations)
